# Generated by Django 5.0.1 on 2024-01-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_newuser_options_alter_newuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
