# Generated by Django 4.2.2 on 2024-02-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_newuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
