# Generated by Django 4.2.2 on 2024-02-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0006_newuser_fav_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='fav_product',
        ),
        migrations.AddField(
            model_name='newuser',
            name='fav_product',
            field=models.ManyToManyField(blank=True, null=True, to='products.productdb'),
        ),
    ]
