# Generated by Django 4.2.2 on 2024-02-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='razorpay_order_id',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='checkout',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
